use SD;

-- DDL
CREATE TABLE Employe(
	EID INT PRIMARY KEY ,
	ENAME VARCHAR(50),
	EAGE INT,
	EADD VARCHAR(50) DEFAULT 'CAIRO',
	DNAME VARCHAR(50) DEFAULT 'EMPTY',
	HIREDATE DATE DEFAULT getdate(),
)
 

-- WE USE ALTER TO MODIFY TABLES
ALTER TABLE EMPLOYE
ADD SAL INT;
ALTER TABLE EMPLOYE
ALTER COLUMN SAL BIGINT;
ALTER TABLE EMPLOYE DROP COLUMN SAL;

-- REMOVE THE WHOLE TABLE FROM DATABASE
DROP TABLE Employe;

----------------------------------------------------
-- DML QUERIES
-- INSERT UPDATE DELETE

INSERT INTO EMPLOYE(EID,ENAME) -- REST OF COLUMNS SHOULD ALLOW NULL VALUES
VALUES(114,'EBRAHIM');         -- VALUES WITH THE SAME ORDER I CHOSE ABOVE

-- I CAN INSERT MORE THAN ONE ROW WITH THE SAME QUERY

INSERT INTO EMPLOYE(EID,ENAME) 
VALUES(115,'SAAD'),(175,'EMAN'),(169,'SAEED');   -- ADDED 3 ROWS

-- UPDATE ON TABLE
UPDATE EMPLOYE SET EID=100 WHERE ENAME='EBRAHIM'
-- ABOVE , I CHOOSE THE ROW WHICH ENAME=EBRAHIM AND CHANGED ITS ID => 100

-- DELETE

DELETE FROM EMPLOYE WHERE EID=100;-- DELETING THE ROW WHICH HAS EID=100

-- TO DELETE ROW => DELETE
-- TO DELETE COLUMN => ALTER

-- ---------------------------------------------------------------------
-- DQL

SELECT DNAME + ' ' + ENAME AS HI FROM Employe